ALTER TABLE "holotrace"."component_instance" DROP CONSTRAINT "component_instance_package_id_component_package_id_fk";
--> statement-breakpoint
DROP INDEX "holotrace"."component_default_simulation_model_uq";--> statement-breakpoint
ALTER TABLE "holotrace"."circuit_version" ADD COLUMN "ir_schema_version" text DEFAULT 'circuit-ir-v0' NOT NULL;--> statement-breakpoint
ALTER TABLE "holotrace"."component_instance" ADD CONSTRAINT "component_instance_package_component_fk" FOREIGN KEY ("package_id","component_id") REFERENCES "holotrace"."component_package"("id","component_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "holotrace"."component_simulation_model" ADD CONSTRAINT "component_simulation_model_package_component_fk" FOREIGN KEY ("package_id","component_id") REFERENCES "holotrace"."component_package"("id","component_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "component_default_simulation_model_for_package_uq" ON "holotrace"."component_simulation_model" USING btree ("component_id","package_id","engine_id") WHERE "holotrace"."component_simulation_model"."is_default" AND "holotrace"."component_simulation_model"."package_id" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "component_default_simulation_model_without_package_uq" ON "holotrace"."component_simulation_model" USING btree ("component_id","engine_id") WHERE "holotrace"."component_simulation_model"."is_default" AND "holotrace"."component_simulation_model"."package_id" IS NULL;--> statement-breakpoint
ALTER TABLE "holotrace"."circuit_version" ADD CONSTRAINT "circuit_version_ir_schema_version_check" CHECK (length("holotrace"."circuit_version"."ir_schema_version") > 0);--> statement-breakpoint
ALTER TABLE "holotrace"."component_instance" ADD CONSTRAINT "component_instance_package_requires_component_check" CHECK ("holotrace"."component_instance"."package_id" IS NULL OR "holotrace"."component_instance"."component_id" IS NOT NULL);